### ISSUE TITLE
Module Admin. Menu Teams - Can not save changes in Teams

### ISSUE THREAD

**Issue by rompik** [eryar/PipeCAD#10]
Similar issue like for saving changes in MDB. After adding new user to Teams and "saving" it system will not save it. In the same time if I added Team inside User mofication form, I can save changes. In the same time this user will be not included into Team inside Teams form.
https://user-images.githubusercontent.com/12736532/160154921-ec47300e-30fa-4f55-8c6b-d26cdc8098b4.mp4

**Comment by rompik** [comment]
One more screenshot.
![DifferenceBetweenUserTeamsForms](https://user-images.githubusercontent.com/12736532/160155428-3a0ce281-510b-4389-9453-6f7c874ede46.png)

**Comment by eryar** [comment]
Fixed PipeCAD1.0.1
