### ISSUE TITLE
Module Admin. Menu Delete Database - Db file is not deleted

### ISSUE THREAD

**Issue by rompik** [eryar/PipeCAD#12]
After deleting DB in module Admin, db file is not deleted in folder. If after deleting db, to create this db again (with the same db number), db file will be not overwritten, so old db file will be used for re-created db. 

https://user-images.githubusercontent.com/12736532/162537098-88d88b50-d598-4633-9aa4-48045b95b3de.mp4

**Comment by eryar** [comment]
Fixed PipeCAD-1.0.2
