### ISSUE TITLE
Russian Translation File

### ISSUE THREAD

**Issue by rompik** [eryar/PipeCAD#126]
Hello Shing,
Please, can you extract translation file for Russian language. I used a Chinese translation file, but it looks like the Chinese file was not updated after creation, as some menus are missing in it. For example, for primitives:
![image](https://user-images.githubusercontent.com/12736532/201900907-87019b42-9872-43d7-805f-0654185f1be6.png)
Please, can you keep paths to python files in it, if possiple.

**Comment by eryar** [comment]
OK.

Yes, the Chinese translation file is not fully translated. Some text in python need use QT_TRANSLATE_NOOP() instead of tr().

I think it is better keep module name, because of the python code maybe changed often.

**Comment by rompik** [comment]
Initial version is added in pull request https://github.com/eryar/PipeCAD/pull/130
