### ISSUE TITLE
Feature - PIP for Python

### ISSUE THREAD

**Issue by rompik** [eryar/PipeCAD#15]
Is it possible to add PIP package to allow of installing of additional Python libraries manually by user via Python console. It could simplify development by using common Python libraries like Pandas (for reading or writing Excel files).

**Comment by eryar** [comment]
I am not familiar with the PIP of Python. For simplicity I use the Python38.zip. 
I will check this.

**Comment by rompik** [comment]
Ok, np. I just look way how to use already existing Python libraries and don't invent bicycle:) Have you other way for adding new Python packages into PipeCAD?

**Comment by eryar** [comment]
I have set the **plugins** to the **PYTHONPATH**, so you can put the Python packages into **plugins**.

**Comment by eryar** [comment]
I will bundle PIP in the next version.
![pip](https://user-images.githubusercontent.com/8439181/166913477-4e977f02-8063-4a02-8969-abb0999e2c83.png)

**Comment by eryar** [comment]
Give a get-pip.bat file to install PIP automatically.
