### ISSUE TITLE
Development - Duplication of namespaces ( PipeCad / PipeCAD ) 

### ISSUE THREAD

**Issue by rompik** [eryar/PipeCAD#21]
In Python console while typing **Pi** I see 2 namespaces: PipeCad and PipeCAD.  
![Duplicating of namespaces](https://user-images.githubusercontent.com/12736532/165270854-c8daa13e-a9e0-40dd-96bf-c7f10eb45120.png)

What is the purpose of it? Is it possible to remain only one namespace (for example, PipeCAD as it will be aligned with name of program, folders name)
![PipeCAD namespace](https://user-images.githubusercontent.com/12736532/165271823-494402ff-5266-4a87-8dea-56710886cbe2.png)

**Comment by eryar** [comment]
PipeCAD is the module of Python, it is from the folder: plugins\PipeCAD.
PipeCad is the core object.

It is a little confused for developer, but I haven't thought of a good name yet.

**Comment by eryar** [comment]
According to Python Naming Convention, change the PipeCAD module name to pipecad.

If have better module name, will discuss or change it.
