### ISSUE TITLE
Mistake in PipeCAD version

### ISSUE THREAD

**Issue by rompik** [eryar/PipeCAD#22]
After installing version 1.0.9 I still see that PipeCad.Version returns version 1.0.8. 
![image](https://user-images.githubusercontent.com/12736532/165278739-45e6bbf3-c1e0-4d4f-a22e-ae863eeed49b.png)

But I see changes in interface which were implemented in 1.0.9
![image](https://user-images.githubusercontent.com/12736532/165278322-b8f0a585-0b08-4d7e-84ae-1d25fbc72906.png)

**Comment by eryar** [comment]
My mistake, I reload the installation package.
