### ISSUE TITLE
Development - Error of checking PIP version

### ISSUE THREAD

**Issue by rompik** [eryar/PipeCAD#42]
In version 1.0.13 while check of PIP utility version I got error message: 
```batch
Fatal error in launcher: Unable to create process using '"D:\Projects\PipeCAD\x64\Release\python.exe"  "E:\PipeCAD\Scripts\pip.exe" -V': The system cannot find the file specified.  
```
![Error of check PIP version](https://user-images.githubusercontent.com/12736532/171640379-4a88c1e5-249f-4bee-ac5f-b87542c7c661.png)

My PipeCAD installation is installed in folder E:\PipeCAD
![PipeCAD Folders](https://user-images.githubusercontent.com/12736532/171640384-2f6151f1-bc4e-4af5-a96b-487699adf5f4.png)

Please, can you check if any paths have to be fixed to use PIP functionality.

**Comment by eryar** [comment]
Okay, I will check this.

**Comment by eryar** [comment]
I can use pip, what is the possible problem?
Set python.exe folder to PATH enviroment and have a try?

![image](https://user-images.githubusercontent.com/8439181/171797021-67af7c5d-41fc-4a5e-bbf3-a978eaa52bac.png)

**Comment by eryar** [comment]
Use the following command to upgrade pip before use pip:
`python -m pip install --upgrade pip`
![image](https://user-images.githubusercontent.com/8439181/171807838-8cb6e6e1-05e5-4cb6-b00f-cb986f668746.png)

**Comment by rompik** [comment]
Yes, it works! Thank you!

**Comment by rompik** [comment]
After installing pandas library in Admin I tested to import pandas to see if it works. But unfortunately got error of missing bz2 package. 
![image](https://user-images.githubusercontent.com/12736532/171852098-b7c55ab8-9b74-4597-ba4f-bdb0ee886f15.png)
In the same time I installed pandas I got no errors. It could be due to compact size of python bundle integrated into PipeCad. Please, can you integrate the full python bundle to avoid additional steps of defining which packages are still missing in Python.

**Comment by eryar** [comment]
OK, I will check this.

**Comment by eryar** [comment]
Yes, lack _bz2.pyd. I will bundle full python module next version.
![image](https://user-images.githubusercontent.com/8439181/171989755-a45c6a19-5dd0-49ea-9281-b91de37f3079.png)
![image](https://user-images.githubusercontent.com/8439181/171989767-9bccd40c-2721-4a8f-907f-7ad28b14e2eb.png)

**Comment by rompik** [comment]
Thank you! I will check it in new version.

**Comment by rompik** [comment]
Works in ver 1.0.14. Thank you!
