### ISSUE TITLE
Module Admin - Changing Team name is not change name of team in database name

### ISSUE THREAD

**Issue by rompik** [eryar/PipeCAD#47]
When I change Team name, system doesn't change automatically Team name of its databases.
https://user-images.githubusercontent.com/12736532/172024472-ec9739e6-e708-47b9-944b-9595a2f315dc.mp4

**Comment by rompik** [comment]
Issue is not correct as to see updates of Team name in database name there needs just to refresh System Explorer. Similar mechanism in PDMS.

**Comment by eryar** [comment]
OK.
