### ISSUE TITLE
Error of database type during catalog database creation

### ISSUE THREAD

**Issue by rompik** [eryar/PipeCAD#64]
During database creation for Catalogs, the system requires using type **CATE**, but not **CATA** as before. 
![изображение](https://user-images.githubusercontent.com/12736532/174793814-df4427b3-07e8-4e72-a088-3b906ed91553.png)

In the same time, project SAMPLE contains catalogs dbs with correct type **CATA**. 
PipeCAD version 1.0.15.

**Comment by eryar** [comment]
My mistake in check database type.

**Comment by eryar** [comment]
https://github.com/eryar/PipeCAD/releases/tag/1.0.16
