### ISSUE TITLE
Update PipeCad.CreateUser() function

### ISSUE THREAD

**Issue by rompik** [eryar/PipeCAD#66]
Similar way with issue [#38](https://github.com/eryar/PipeCAD/issues/38) there is need to update Core code for function PipeCad.CreateUser() to optimize Python code for creating users and make it more robust for end user. 

Currently, to create a new user, I have to do next steps:
1) Run command PipeCad.CreateUser
2) I have to create TMLI element
3) I have to create LTEA element if I want to add user to dedicated team. 

```python 

PipeCad.CreateUser( user_name, user_description )            

current_user = PipeCad.CurrentItem()
current_user.Description = user_description
current_user.Security = user_security
current_user.Password = user_password

PipeCad.CreateItem("TMLI")
user_tmli = PipeCad.CurrentItem()

for i in range ( len( user_teams ) ):
    
    select_user_tmli = PipeCad.SetCurrentItem( user_tmli )
    user_tmli = PipeCad.CurrentItem()
    
    PipeCad.CreateItem("LTEA")
    user_ltea = PipeCad.CurrentItem()
    
    select_user_team = PipeCad.SetCurrentItem("/*" + user_teams[i])
    user_team = PipeCad.CurrentItem()
     
    user_ltea.Temf = user_ltea
```

After update PipeCad.CreateUser() I think that compacted python can be next: 
```python
user = PipeCad.CreateUser( user_name, user_password, user_description, user_security, user_teams ) 
```
where:
 user_name - type string
 user_password - type string
 user_description - type string
 user_security - type string
 user_teams - type list or array of unique Teams

Element TMLI, which required for core for correct work, have to be created by core itself. 

For adding user to team can be done by using next code:
```python
user = PipeCad.CurrentItem()
user.AddTeam(user_team)
```
or for several teams
```python
user.AddTeams(user_teams)    
```
Where users_teams - list of Teams. If some team from the list is already is added to user, method will just skip adding duplicates

**Comment by eryar** [comment]
Ok, will fix in next version.

**Comment by eryar** [comment]
Add PipeCad.CreateUser(QString theName, QString theDescription, QString thePassword, QString theSecurity, QList<TreeItem*> theTeamList) function:
![image](https://user-images.githubusercontent.com/8439181/175476364-5a2bb273-a61a-4f3e-bc2b-241dceeb38f9.png)

**Comment by eryar** [comment]
For user to team, use the User JoinTeam() function:
- JoinTeam(theTeamItem)
- JoinTeam(theTeamList)

![image](https://user-images.githubusercontent.com/8439181/175477216-9d19a3f3-9f13-4b99-b787-ca7335292e13.png)

**Comment by rompik** [comment]
Thank you! Does it included into version 1.0.16?

**Comment by eryar** [comment]
Yes, It will included into 1.0.16.

**Comment by rompik** [comment]
Please can you upload installator of version 1.0.16 as currently is only Python codes are available.

**Comment by eryar** [comment]
Sorry, fogot to upload setup.exe yesterday. You can download it now.

**Comment by eryar** [comment]
https://github.com/eryar/PipeCAD/releases/tag/1.0.16

**Comment by eryar** [comment]
OK, I will check it before join the team.

**Comment by eryar** [comment]
Use QMap to remove duplicates and sort team by refno.

**Comment by eryar** [comment]
https://github.com/eryar/PipeCAD/releases/tag/1.0.17
