### ISSUE TITLE
Status Bar + Progress Bar

### ISSUE THREAD

**Issue by rompik** [eryar/PipeCAD#68]
Please, can you add to Core Status bar and Progress bar in it to have opportunity to show progress for long-running tasks (like doing something in the loop) or show some messages in Status bar. 
For access to it, I think can be used next code like example:
```python
PipeCad.Progress.setValue(14.3)       # PipeCad will show progress 14.3%
PipeCad.Progress.setValue(0)           # PipeCad will hide progress bar - similar like in PDMS
PipeCad.Status.setText("Some message for status bar")
```
I tried to add Progress bar to Python code, but during database creation task in the loop after some time whole PipeCad interface was freezed:( So PythonQt progress bar is not good for "heavy" tasks :(

**Comment by rompik** [comment]
![image](https://user-images.githubusercontent.com/12736532/175511432-9d80ec96-8d7f-4711-96b1-c637d20bef56.png)

**Comment by eryar** [comment]
OK,
I will add function to use progress bar and status bar in main window.

**Comment by eryar** [comment]
Now the status bar already exposed in PipeCad:
![image](https://user-images.githubusercontent.com/8439181/175536921-1401dff0-fb58-40e6-a88a-08a2f7a43d7c.png)

**Comment by eryar** [comment]
Yes, It should be.
For your case I think need use multi-thread to avoid progress bar freezed.

**Comment by rompik** [comment]
Currently Issue will be closed as status bar and progress bar is available now. For multi-thread, I will need to check possibilities.
