### ISSUE TITLE
Error of importing PythonQt.QtWebKit

### ISSUE THREAD

**Issue by rompik** [eryar/PipeCAD#72]
I try to make Help Viewer for PipeCAD to view md documentation copied from GitHub to folder %PIPECAD_EXE_PATH%\help. Utility will collect all language folders (now they are empty) to provide ability to select documentation language from the list:
![изображение](https://user-images.githubusercontent.com/12736532/176655207-df5ebf88-cd02-4e91-867a-58b3620608d0.png)

For this purpose, I tried to import QWebKit, which has to be included to PythonQt, but got error: 
![изображение](https://user-images.githubusercontent.com/12736532/176653256-c550e280-2e4b-4c64-bc37-7e620e302bc7.png)

Please can you advise if how can I import QWebKit module or maybe you can advise another way for rendering md pages?

**Comment by eryar** [comment]
I have not compile QtWebKit in PythonQt to avoid dlls size.
I will compile QtWebKit in PythonQt next version.

**Comment by eryar** [comment]
Hello Roman,

I think about to introduce QtWebKit module for PipeCAD carefully. 
Now PipeCAD only depend on Qt modules from qtbase source code,
 compile QtWebKit will introduce lots of Qt modules, such as QtQuick, 
QtQml, QtPositionning, .etc.

I want to simplify the documents to open *.pdf directly according to the language.
I will build *.pdf from *.md by Doxygen and MiKTeX and upload the language folder.

What do you think?

**Comment by eryar** [comment]
Or build *.chm by Doxygen on Windows.

**Comment by rompik** [comment]
Hello Shing, 
Sorry, I'm new in Qt and I didn't know, that adding module will requires to compile a lot of depends. So let's leave PipeCAD core as is for the current moment. 
I think, currently, we can use a single PDF file for documentation (at the least for printing). 
In the same time, documentation in *.chm looks more powerful in case of navigation and searching inside of documentation. In this case, it can set up GitHub Action to compile *.md to *.chm files automatically. So, users will be able to download the latest documentation from GitHub w/out waiting new version of PipeCAD (and also we can add function to PipeCad to check version of documentation and download it automatically).

**Comment by eryar** [comment]
OK.

PDF file also have navigation function and can be viewed in different OS;

Yes, In Windows *.chm is more powerful, I will learn to use Github Action to compile *.md to *.chm.
