### ISSUE TITLE
Adding new Form

### ISSUE THREAD

**Issue by rompik** [eryar/PipeCAD#90]
Hello Shing,
Please, can you write steps for adding new form to PipeCAD library. Currently, I have to use existing library files if I want to add new form to any module. I tried to create new file for new form but I can't find way how to start it in PipeCad. For example, I created new file NewForm.py with next code:
```python 
from PythonQt.QtCore import *
from PythonQt.QtGui import *
from PythonQt.QtSql import *

from pipecad import *

class TestFormDlg(QDialog):
    def __init__(self, parent = None):
        QDialog.__init__(self, parent)
        self.setupUi()
    # __init__

    def setupUi(self):
        self.resize(500, 360)
        self.setWindowTitle(self.tr("Detail Text Definition"))

        self.verticalLayout = QVBoxLayout(self)
        self.labelTtext = QLabel("Ttext")
        self.verticalLayout.addLayout(labelTtext)

    # setupUi

# Singleton Instance.
aTestFormDlg = TestFormDlg(PipeCad)

def ShowNewForm():
    aTestFormDlg.show()
# Show
```
To start form in Admin I tried to use command: 
```python 
NewForm.ShowNewForm()
```
but got error that form is not defined:
![изображение](https://user-images.githubusercontent.com/12736532/182357108-8f214acf-a3bf-4cb4-a9cc-3def72b7fa94.png)

Do I need to do something else to run my form? Or maybe I need to register form inside PipeCAD?

**Comment by eryar** [comment]
Hello Roman,

In Python a *.py is a **Module**, and the file name is the module name. Before you use the module's class/methods, you should import it first:
```python
import NewForm
NewForm.ShowNewForm()
````

**Comment by rompik** [comment]
Thank you for explanation!
Just found that also need to add **pipecad** before module name for correct loading:
```python
import pipecad.NewForm
NewForm.ShowNewForm()
```

**Comment by eryar** [comment]
Yes, if you put the **NewForm.py** in **pipecad** folder.

In Python a folder with **__init__.py** is a package. You can define your package in PYTHON_LIB folder.
